export const STATUS_OPTIONS = [
    "new",
    "in-kitchen",
    "ready",
    "delivered",
    "billing-requested",
    "paid",
    "completed",
]


export const FOOD_CATEGORIES = [
    "Appetizers",
    "Salads",
    "Soups",
    "Main Courses",
    "Grilled",
    "Pizza",
    "Pasta",
    "Burgers",
    "Sandwiches",
    "Shawarma",
    "Fried Chicken",
    "Seafood",
    "Rice Dishes",
    "Sushi",
    "Vegetarian",
    "Vegan",
    "Desserts",
    "Ice Cream",
    "Beverages",
    "Hot Drinks",
    "Cold Drinks",
    "Smoothies",
    "Breakfast",
    "Brunch",
    "Kids Menu",
    "Special Offers",
    "Side Dishes",
    "Bakery",
    "Wraps",
    "Tacos",
    "Steaks",
    "Kebabs",
    "Mezza",
    "Arabic Food",
    "Indian Food",
    "Chinese Food",
    "Mexican Food",
    "Thai Food",
    "Japanese Food",
    "Turkish Food"
];